### ISSUE TITLE
Model is not cached locally and an error occurred while trying to fetch metadata from the Hub

### ISSUE THREAD

**Issue by siraxe** [kijai/ComfyUI-DiffusersSD3Wrapper#1]
It did download the model but can't access it ?
![image](https://github.com/kijai/ComfyUI-DiffusersSD3Wrapper/assets/27487254/4380e300-b615-4913-b3d9-5d3760129dd2)

**Comment by kijai** [comment]
That's just the controlnet model, that was downloaded correctly yes. 

The error is about the SD3 diffusers model itself, since it's in stabilityAI's gated repository, it can't be downloaded without logging in hugginface, so for it to auto download you need to give the node your hugginface access token, just for the first run. You can generate access token from Hugginface account settings.

**Comment by siraxe** [comment]
> That's just the controlnet model, that was downloaded correctly yes.
> 
> The error is about the SD3 diffusers model itself, since it's in stabilityAI's gated repository, it can't be downloaded without logging in hugginface, so for it to auto download you need to give the node your hugginface access token, just for the first run. You can generate access token from Hugginface account settings.

Ah , I'm stupid , sorry.
All good , needed token for HF diffusers )
![image](https://github.com/kijai/ComfyUI-DiffusersSD3Wrapper/assets/27487254/43d68a22-7f0e-4ff8-a147-c24f9db3d699)

**Comment by siraxe** [comment]
downloaded and token seems fine I think , but still having some issues running it after ...
![image](https://github.com/kijai/ComfyUI-DiffusersSD3Wrapper/assets/27487254/19a58660-2d1d-4439-93e0-54e9ff16e35a)
![image](https://github.com/kijai/ComfyUI-DiffusersSD3Wrapper/assets/27487254/fcf26b91-8dc4-440a-9136-487b9ddd4764)

**Comment by kijai** [comment]
Can't say I recognize that error, maybe something to do with transformers version? I'm running `transformers==4.39.3` myself.

**Comment by siraxe** [comment]
> Can't say I recognize that error, maybe something to do with transformers version? I'm running `transformers==4.39.3` myself.

Thank you!  You're right I had older transformers version
![image](https://github.com/kijai/ComfyUI-DiffusersSD3Wrapper/assets/27487254/a6c23045-54b3-4ead-a427-96b968244765)
